# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/messages.proto\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x92\x01\n\rErrorResponse\x12\x12\n\nerror_code\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\x12,\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x1b.ErrorResponse.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa6\x01\n\x06Packet\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12$\n\x0c\x65\x63ho_request\x18\n \x01(\x0b\x32\x0c.EchoRequestH\x00\x12&\n\recho_response\x18\x0b \x01(\x0b\x32\r.EchoResponseH\x00\x12 \n\x05\x65rror\x18\xe7\x07 \x01(\x0b\x32\x0e.ErrorResponseH\x00\x42\t\n\x07payloadb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERRORRESPONSE_DETAILSENTRY._options = None
  _ERRORRESPONSE_DETAILSENTRY._serialized_options = b'8\001'
  _ECHOREQUEST._serialized_start=25
  _ECHOREQUEST._serialized_end=55
  _ECHORESPONSE._serialized_start=57
  _ECHORESPONSE._serialized_end=88
  _ERRORRESPONSE._serialized_start=91
  _ERRORRESPONSE._serialized_end=237
  _ERRORRESPONSE_DETAILSENTRY._serialized_start=191
  _ERRORRESPONSE_DETAILSENTRY._serialized_end=237
  _PACKET._serialized_start=240
  _PACKET._serialized_end=406
# @@protoc_insertion_point(module_scope)
